twig:
    file_name_pattern: '*.twig'
    globals:
        webapp_title: 'pushcat'
        twitter_href: 'https://twitter.com/pushcatsol'
        telegram_href: 'https://t.me/pushcatsol'
        pumpfun_href: 'https://pump.fun/'
        #dexscreener_href: 'https://dexscreener...'

when@test:
    twig:
        strict_variables: true
